### PR TITLE
Add fi01

### PR DESCRIPTION
**Pull request by lvarin**

### CODE REVIEW

**Review by gmauro — COMMENTED** [review]
tf directory contains terraform files that are used as a template for the most general use case. Instead, fi01 is the directory for your own instance and is the right place where update/modify terraform files accordingly with your infrastructure specifications. So, please, I have to ask you to remove this commit 4bc5c95  from the PR

**Review by gmauro — COMMENTED** [review]
Have you forgotten to rebase your commits?

**Review by gmauro — COMMENTED** [review]
Have you forgotten to rebase your commits?

**Comment by lvarin** [comment]
I have just seen this mess I created, I will fix it.

**Comment by lvarin** [comment]
I will close this and start from the beginning, sorry for the mess.

**Pull request closed without merging**
